import AnimatedText from '@/components/AnimatedText'
import HireMe from '@/components/HireMe'
import { LinkArrow } from '@/components/Icons'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'
import profileImg from '../../public/images/profile/developer-pic-1.png'
import TransitionEffect from '@/components/TransitionEffect'
export default function Home() {
  return (
    <>
      <Head>
        <title>خانه</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light ">
        <Layout className="pt-0 md:pt-16 sm:pt-8 ">
          <div className="flex items-center justify-center w-full  ">
            <div className="flex items-center justify-between w-full lg:flex-col">
              <div className="w-1/2 md:w-full">
                <Image
                  src={profileImg}
                  priority
                  className="w-full h-auto lg:hidden md:inline-block md:w-full "
                  alt="portfolio"
                  sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw"
                />
              </div>
              <div className="w-1/2 flex flex-col gap-8 items-center self-center lg:w-full lg:text-center ">
                <AnimatedText
                  text={'طراحی و ساخت وبسایت '}
                  className="!text--right xl:!text-3xl lg:!text-center lg:!text-4xl md:!text-3xl sm:!text-3xl "
                />
                <p className="my-4 text-center max-w-md text-base font-medium md:text-sm sm:text-xs ">
                  به عنوان یک طراح و سازنده سایت فول استک، میخواهم بوسیله
                  تکنولوژیهای روز طراحی و ساخت را انجام دهم. متن از پیش ساخته
                  برای طراحی.
                </p>
                <div className="flex items-center self-center mt-2 lg:self-center ">
                  <Link
                    href="/dummy.pdf"
                    target={'_blank'}
                    className="flex items-center bg-dark text-light p-2.5 mr-8 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:text-dark dark:bg-light hover:dark:text-light hover:dark:bg-dark hover:dark:border-light md:p-2 md:px-4 md:text-base "
                    download
                  >
                    رزومه
                    <LinkArrow className={'w-6 mr-2'} />
                  </Link>
                  <Link
                    href="mailto:saeedmihmnaparast@gmail.com"
                    target={'_blank'}
                    className="mr-6 text-xl  font-medium text-dark underline underline-offset-4 dark:text-light md:text-base "
                  >
                    تماس
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute left-8 bottom-8 inline-block w-24 md:hidden ">
          <Image src={lightBulb} alt="Saeed" className="w-full h-auto" />
        </div>
      </main>
    </>
  )
}
